baseURL = 'https://madsmogensen.dk/'
languageCode = 'en-us'
title = "Mads' blog"
theme = 'custom'

[markup]
  [markup.highlight]
  lineNos = true
  style = 'onedark'
  tabWidth = 2

  [markup.goldmark]
    [markup.goldmark.parser]
    wrapStandAloneImageWithinParagaph = false

      [markup.goldmark.parser.attribute]
      block = true


[caches]
  [caches.images]
    dir = ':cacheDir/images'

